$SCREENLOCK = pidof hyprlock || hyprlock

general {
    lock_cmd = $SCREENLOCK
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Diminue la luminosité après 5 minutes
listener {
    timeout = 300
    on-timeout = brightnessctl -s && brightnessctl s 10%
    on-resume = brightnessctl -r
}

# Verrouille après 10 minutes
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Éteint l'écran après 15 minutes
listener {
    timeout = 900
    on-timeout = Hyde run audio_idle ; hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend après 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
