# ─────────────────────────────────────────
# VARIABLES
# ─────────────────────────────────────────
$fontFamily = JetBrainsMono Nerd Font
$wallpaper = /home/Zavar/Images/Fantasy.png

# ─────────────────────────────────────────
# COULEURS
# ─────────────────────────────────────────
$c1_rgba = rgba(255,255,255,1.0)
$c2_rgba = rgba(0,0,0,1.0)

# ─────────────────────────────────────────
# GENERAL
# ─────────────────────────────────────────
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# ─────────────────────────────────────────
# BACKGROUND
# ─────────────────────────────────────────
background {
    monitor =
    path = $wallpaper
    blur_size = 2
    blur_passes = 1
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# ─────────────────────────────────────────
# DAY
# ─────────────────────────────────────────
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A" | tr '[:lower:]' '[:upper:]')"
    color = $c1_rgba
    font_size = 160
    font_family = Anurati
    position = 0, 100
    halign = center
    valign = center
}

# ─────────────────────────────────────────
# DATE
# ─────────────────────────────────────────
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%B %d")"
    color = $c1_rgba
    font_size = 35
    font_family = $fontFamily
    position = 0, -20
    halign = center
    valign = center
}

# ─────────────────────────────────────────
# TIME
# ─────────────────────────────────────────
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I:%M %p")"
    color = $c1_rgba
    font_size = 35
    font_family = $fontFamily
    position = 0, 780
    halign = center
    valign = bottom
}

# ─────────────────────────────────────────
# INPUT FIELD
# ─────────────────────────────────────────
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = $c1_rgba
    fade_on_empty = true
    fade_timeout = 1000
    hide_input = false
    rounding = -1
    check_color = rgba(188, 229, 255, 1)
    fail_color = rgba(255, 0, 0, 1)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = true
    position = 0, 80
    halign = center
    valign = bottom
}

# ─────────────────────────────────────────
# USER
# ─────────────────────────────────────────
label {
    monitor =
    text =   $USER
    color = $c1_rgba
    font_size = 18
    font_family = Anutari
    position = 0, 30
    halign = center
    valign = bottom
}
